### PR TITLE
Adding robsears to CODEOWNERS

### PR DESCRIPTION
**Pull request by dtaivpp**
### Description
Adding robsears to CODEOWNERS

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
@dtaivpp Looks like @robsears hasn't been active, and his permissions were revoked for inactivity - will you email him on whether he wants to stay as a maintainer, or be moved to emeritus (in which case the change should be made in MAINTAINERS)?

**Comment by dtaivpp** [comment]
I'll reach out

**Comment by dblock** [comment]
@dtaivpp Did you hear back?

**Comment by dtaivpp** [comment]
Yes, he is not able to continue for now so lets move him to emeritus.

**Comment by dtaivpp** [comment]
Removed him but otherwise updated the file.

**Comment by dblock** [comment]
Superseded with https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/pull/37.

**Pull request closed without merging**
