### PR TITLE
Update rubygems public key until 20250726

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Update rubygems public key until 20250726

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-build/issues/4893

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Earlopain** [comment]
Openend https://github.com/aws/aws-sdk-ruby/pull/3075 for the test failures

**Comment by nhtruong** [comment]
Looks like we'll have to wait for a new release of `aws-sdk-ruby`. Good thing this gem very rarely needs a release.

**Review by nhtruong — APPROVED** [review]

**Comment by dblock** [comment]
Looks like `./gradlew :distribution:archives:linux-tar:assemble` is failing for one of the tests, and it's not a fluke.

**Comment by peterzhuamazon** [comment]
Seems like 1.9.1 has been released according to:
* https://github.com/aws/aws-sdk-ruby/pull/3075#issuecomment-2258815491

cc @nhtruong @Earlopain Can we re-run the test or is there additional changes to consume the new sdk version? Thanks!

**Comment by peterzhuamazon** [comment]
Seems like the failure is related to `2.0`: https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/actions/runs/10119006936/job/28118732096?pr=43
```

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':buildSrc:test'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':buildSrc:runtimeClasspath'.
      > Could not find com.netflix.nebula:nebula-core:3.0.0.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/netflix/nebula/nebula-core/3.0.0/nebula-core-3.0.0.pom
          - https://plugins.gradle.org/m2/com/netflix/nebula/nebula-core/3.0.0/nebula-core-3.0.0.pom
        Required by:
            project :buildSrc > com.netflix.nebula:nebula-publishing-plugin:4.4.4

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

We probably should not test 2.0 anymore since that branch is not maintained anymore.
Also I dont think this PR changes has anything to do with the failure.


Can we go ahead and merge this PR?
Thanks!

**Comment by nhtruong** [comment]
@peterzhuamazon let's remove 2.0 from the matrix in this PR as well if you dont mind :)

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon let's remove 2.0 from the matrix in this PR as well if you dont mind :)

Send a new PR on this: https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/pull/44

Thanks.

**Comment by peterzhuamazon** [comment]
Rebased this branch.

**Pull request merged**
